# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Betzerra
email: ezequiel@betzerra.com
description: >
  iOS Software Engineer living in Buenos Aires ğŸ‡¦ğŸ‡·.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://betzerra.github.io"
twitter_username: betzerra
github_username:  betzerra

# Build settings
markdown: kramdown

plugins:
  - jekyll-gist
